server:
  address: "3.234.143.13"
  user: "ec2-user"
  port: 22
  dir: "newproject"
repository:
  url: "git@github.com:dung13890/deploy-tool.git"
  branch: "master"
  # tag: "1.0.2"
shared:
  folders:
    - "vendor"
    - "node_modules"
  files:
    - ".env"
tasks:
  - "echo 'xin chao'"
cluster:
  hosts:
    - "127.0.0.1"
  rsync:
    excludes:
      - ".env"
      - "*.log"
  cmds:
    - "ls -al"


